country_to_currency = {
    "united arab emirates": "AED",
    "afghanistan": "AFN",
    "albania": "ALL",
    "armenia": "AMD",
    "netherlands antilles": "ANG",
    "angola": "AOA",
    "argentina": "ARS",
    "australia": "AUD",
    "aruba": "AWG",
    "azerbaijan": "AZN",
    "bosnia": "BAM",
    "herzegovina": "BAM",
    "barbados": "BBD",
    "bangladesh": "BDT",
    "bulgaria": "BGN",
    "bahrain": "BHD",
    "burundi": "BIF",
    "bermuda": "BMD",
    "brunei": "BND",
    "bolivia": "BOB",
    "brazil": "BRL",
    "bahamas": "BSD",
    "bhutan": "BTN",
    "botswana": "BWP",
    "belarus": "BYN",
    "belize": "BZD",
    "canada": "CAD",
    "congo": "CDF",
    "switzerland": "CHF",
    "chile": "CLP",
    "china": "CNY",
    "colombia": "COP",
    "costa rica": "CRC",
    "cuba": "CUP",
    "cape verde": "CVE",
    "czech republic": "CZK",
    "djibouti": "DJF",
    "denmark": "DKK",
    "dominican Republic": "DOP",
    "algeria": "DZD",
    "egypt": "EGP",
    "eritrea": "ERN",
    "ethiopia": "ETB",
    "austria": "EUR",
    "belgium": "EUR",
    "croatia": "EUR",
    "cyprus": "EUR",
    "estonia": "EUR",
    "finland": "EUR",
    "france": "EUR",
    "germany": "EUR",
    "greece": "EUR",
    "ireland": "EUR",
    "italy": "EUR",
    "latvia": "EUR",
    "lithuania": "EUR",
    "luxembourg": "EUR",
    "malta": "EUR",
    "netherlands": "EUR",
    "portugal": "EUR",
    "slovakia": "EUR",
    "slovenia": "EUR",
    "spain": "EUR",
    "fiji": "FJD",
    "falkland islands": "FKP",
    "faroe islands": "FOK",
    "united kingdom": "GBP",
    "georgia": "GEL",
    "guernsey": "GGP",
    "ghana": "GHS",
    "gibraltar": "GIP",
    "the gambia": "GMD",
    "guinea": "GNF",
    "guatemala": "GTQ",
    "guyana": "GYD",
    "hong kong": "HKD",
    "honduras": "HNL",
    "haiti": "HTG",
    "hungary": "HUF",
    "indonesia": "IDR",
    "israel": "ILS",
    "isle of man": "IMP",
    "india": "INR",
    "iraq": "IQD",
    "iran": "IRR",
    "iceland": "ISK",
    "jersey": "JEP",
    "jamaica": "JMD",
    "jordan": "JOD",
    "japan": "JPY",
    "kenya": "KES",
    "kyrgyzstan": "KGS",
    "cambodia": "KHR",
    "kiribati": "KID",
    "comoros": "KMF",
    "south korea": "KRW",
    "kuwait": "KWD",
    "cayman islands": "KYD",
    "kazakhstan": "KZT",
    "laos": "LAK",
    "lebanon": "LBP",
    "sri lanka": "LKR",
    "liberia": "LRD",
    "lesotho": "LSL",
    "libya": "LYD",
    "morocco": "MAD",
    "moldova": "MDL",
    "madagascar": "MGA",
    "north macedonia": "MKD",
    "myanmar": "MMK",
    "mongolia": "MNT",
    "macau": "MOP",
    "mauritania": "MRU",
    "mauritius": "MUR",
    "maldives": "MVR",
    "Malawi": "MWK",
    "Mexico": "MXN",
    "Malaysia": "MYR",
    "Mozambique": "MZN",
    "Namibia": "NAD",
    "nigeria": "NGN",
    "Nicaragua": "NIO",
    "Norway": "NOK",
    "Nepal": "NPR",
    "New Zealand": "NZD",
    "Oman": "OMR",
    "Panama": "PAB",
    "Peru": "PEN",
    "Papua New Guinea": "PGK",
    "Philippines": "PHP",
    "Pakistan": "PKR",
    "Poland": "PLN",
    "Paraguay": "PYG",
    "Qatar": "QAR",
    "Romania": "RON",
    "Serbia": "RSD",
    "Russia": "RUB",
    "Rwanda": "RWF",
    "Saudi Arabia": "SAR",
    "Solomon Islands": "SBD",
    "Seychelles": "SCR",
    "Sudan": "SDG",
    "Sweden": "SEK",
    "Singapore": "SGD",
    "Saint Helena": "SHP",
    "Sierra Leone": "SLE",
    "Somalia": "SOS",
    "Suriname": "SRD",
    "South Sudan": "SSP",
    "São Tomé and Príncipe": "STN",
    "Syria": "SYP",
    "Eswatini": "SZL",
    "Thailand": "THB",
    "Tajikistan": "TJS",
    "Turkmenistan": "TMT",
    "Tunisia": "TND",
    "Tonga": "TOP",
    "Turkey": "TRY",
    "Trinidad and Tobago": "TTD",
    "Tuvalu": "TVD",
    "Taiwan": "TWD",
    "Tanzania": "TZS",
    "Ukraine": "UAH",
    "Uganda": "UGX",
    "united states": "USD",
    "uruguay": "UYU",
    "uzbekistan": "UZS",
    "venezuela": "VES",
    "vietnam": "VND",
    "vanuatu": "VUV",
    "samoa": "WST",
    "cemac": "XAF",
    "organisation of eastern caribbean states": "XCD",
    "international monetary fund": "XDR",
    "cfa": "XOF",
    "collectivités d'outre-mer": "XPF",  # CFP Franc
    "yemen": "YER",
    "south africa": "ZAR",
    "zambia": "ZMW",
    "zimbabwe": "ZWL"
}

country_to_currency = {
    country.lower(): code
    for country, code in country_to_currency.items()
}
country_aliases = {
    "uk":            "united kingdom",
    "gb":            "united kingdom",
    "usa":           "united states",
    "us":            "united states",
    "sa":            "south africa",
    "uae":           "united arab emirates",
    "korea":         "south korea",
    "saudi":          "saudi arabia",
    "trinidad":       "trinidad and tobago",
    "tobago":         "trinidad and tobago",
}